// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoDeFutbol.App.Persistencia;

namespace TorneoDeFutbol.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210926043153_ModifEntidades")]
    partial class ModifEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Colegio", b =>
                {
                    b.Property<int>("Id_Colegio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Colegio");

                    b.ToTable("Colegios");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.DatosPartido", b =>
                {
                    b.Property<int>("Id_DatosPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Goles_L")
                        .HasColumnType("int");

                    b.Property<int>("Goles_V")
                        .HasColumnType("int");

                    b.Property<int>("Marcador")
                        .HasColumnType("int");

                    b.Property<int>("Tarjetas_Amarillas")
                        .HasColumnType("int");

                    b.Property<int>("Tarjetas_Rojas")
                        .HasColumnType("int");

                    b.Property<int>("Tiempo")
                        .HasColumnType("int");

                    b.Property<int?>("equipoId_Equipo")
                        .HasColumnType("int");

                    b.HasKey("Id_DatosPartido");

                    b.HasIndex("equipoId_Equipo");

                    b.ToTable("DatosPartidos");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id_Equipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("directorTecnicoId_Participante")
                        .HasColumnType("int");

                    b.Property<int?>("jugadorId_Participante")
                        .HasColumnType("int");

                    b.Property<int?>("municipioId_Municipio")
                        .HasColumnType("int");

                    b.Property<int?>("registroPartidos_Jugados")
                        .HasColumnType("int");

                    b.HasKey("Id_Equipo");

                    b.HasIndex("directorTecnicoId_Participante");

                    b.HasIndex("jugadorId_Participante");

                    b.HasIndex("municipioId_Municipio");

                    b.HasIndex("registroPartidos_Jugados");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("Id_Estadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("municipioId_Municipio")
                        .HasColumnType("int");

                    b.HasKey("Id_Estadio");

                    b.HasIndex("municipioId_Municipio");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id_Municipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Municipio");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Participante", b =>
                {
                    b.Property<int>("Id_Participante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Participante");

                    b.ToTable("Participantes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Participante");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Partido", b =>
                {
                    b.Property<int>("Id_Partido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("EquipoLocal")
                        .HasColumnType("bit");

                    b.Property<bool>("EquipoVisitante")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Marcador")
                        .HasColumnType("int");

                    b.Property<int?>("arbitroId_Participante")
                        .HasColumnType("int");

                    b.Property<int?>("datospartidoId_DatosPartido")
                        .HasColumnType("int");

                    b.Property<int?>("equipoId_Equipo")
                        .HasColumnType("int");

                    b.Property<int?>("estadioId_Estadio")
                        .HasColumnType("int");

                    b.HasKey("Id_Partido");

                    b.HasIndex("arbitroId_Participante");

                    b.HasIndex("datospartidoId_DatosPartido");

                    b.HasIndex("equipoId_Equipo");

                    b.HasIndex("estadioId_Estadio");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Registro", b =>
                {
                    b.Property<int>("Partidos_Jugados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Goles_Contra")
                        .HasColumnType("int");

                    b.Property<int>("Goles_Favor")
                        .HasColumnType("int");

                    b.Property<int>("Partidos_Empatados")
                        .HasColumnType("int");

                    b.Property<int>("Partidos_Ganados")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Partidos_Jugados");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Arbitro", b =>
                {
                    b.HasBaseType("TorneoDeFutbol.App.Dominio.Participante");

                    b.Property<int?>("colegioId_Colegio")
                        .HasColumnType("int");

                    b.Property<int?>("participanteId_Participante")
                        .HasColumnType("int")
                        .HasColumnName("Arbitro_participanteId_Participante");

                    b.HasIndex("colegioId_Colegio");

                    b.HasIndex("participanteId_Participante");

                    b.HasDiscriminator().HasValue("Arbitro");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Director_Tecnico", b =>
                {
                    b.HasBaseType("TorneoDeFutbol.App.Dominio.Participante");

                    b.Property<int?>("participanteId_Participante")
                        .HasColumnType("int")
                        .HasColumnName("Director_Tecnico_participanteId_Participante");

                    b.HasIndex("participanteId_Participante");

                    b.HasDiscriminator().HasValue("Director_Tecnico");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Jugador", b =>
                {
                    b.HasBaseType("TorneoDeFutbol.App.Dominio.Participante");

                    b.Property<int>("NumCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("participanteId_Participante")
                        .HasColumnType("int");

                    b.HasIndex("participanteId_Participante");

                    b.HasDiscriminator().HasValue("Jugador");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.DatosPartido", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Equipo", "equipo")
                        .WithMany()
                        .HasForeignKey("equipoId_Equipo");

                    b.Navigation("equipo");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Equipo", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Director_Tecnico", "directorTecnico")
                        .WithMany()
                        .HasForeignKey("directorTecnicoId_Participante");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Jugador", "jugador")
                        .WithMany()
                        .HasForeignKey("jugadorId_Participante");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Municipio", "municipio")
                        .WithMany()
                        .HasForeignKey("municipioId_Municipio");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Registro", "registro")
                        .WithMany()
                        .HasForeignKey("registroPartidos_Jugados");

                    b.Navigation("directorTecnico");

                    b.Navigation("jugador");

                    b.Navigation("municipio");

                    b.Navigation("registro");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Estadio", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Municipio", "municipio")
                        .WithMany()
                        .HasForeignKey("municipioId_Municipio");

                    b.Navigation("municipio");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Partido", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Arbitro", "arbitro")
                        .WithMany()
                        .HasForeignKey("arbitroId_Participante");

                    b.HasOne("TorneoDeFutbol.App.Dominio.DatosPartido", "datospartido")
                        .WithMany()
                        .HasForeignKey("datospartidoId_DatosPartido");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Equipo", "equipo")
                        .WithMany()
                        .HasForeignKey("equipoId_Equipo");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Estadio", "estadio")
                        .WithMany()
                        .HasForeignKey("estadioId_Estadio");

                    b.Navigation("arbitro");

                    b.Navigation("datospartido");

                    b.Navigation("equipo");

                    b.Navigation("estadio");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Arbitro", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Colegio", "colegio")
                        .WithMany()
                        .HasForeignKey("colegioId_Colegio");

                    b.HasOne("TorneoDeFutbol.App.Dominio.Participante", "participante")
                        .WithMany()
                        .HasForeignKey("participanteId_Participante");

                    b.Navigation("colegio");

                    b.Navigation("participante");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Director_Tecnico", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Participante", "participante")
                        .WithMany()
                        .HasForeignKey("participanteId_Participante");

                    b.Navigation("participante");
                });

            modelBuilder.Entity("TorneoDeFutbol.App.Dominio.Jugador", b =>
                {
                    b.HasOne("TorneoDeFutbol.App.Dominio.Participante", "participante")
                        .WithMany()
                        .HasForeignKey("participanteId_Participante");

                    b.Navigation("participante");
                });
#pragma warning restore 612, 618
        }
    }
}
